version: "2"

services:
  pihole-server:
    image: pihole/pihole:${PIHOLE_DOCKER_TAG}
    container_name: pihole-server
    restart: always
    networks:
      macvlan_network:
        ipv4_address: ${DNS_IP_ADDRESS}
    cap_add:
      - NET_ADMIN
    volumes:
      - ${PIHOLE_BASE_DIRECTORY}/pihole/:/etc/pihole/
      - ${PIHOLE_BASE_DIRECTORY}/dnsmasq.d/:/etc/dnsmasq.d/
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      DNSMASQ_LISTENING: all
      TZ: ${TIMEZONE}
      ServerIP: ${DNS_IP_ADDRESS}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      DELAY_STARTUP: 20

  nginx-server:
    image: jc21/nginx-proxy-manager:${NGINX_SERVER_DOCKER_TAG}
    container_name: nginx-proxy
    restart: unless-stopped
    networks:
      macvlan_network:
        ipv4_address: ${PROXY_IP_ADDRESS}
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ${NGNIX_PROXY_MANAGER_BASE_DIRECTORY}/data:/data
      - ${NGNIX_PROXY_MANAGER_BASE_DIRECTORY}/letsencrypt:/etc/letsencrypt
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: "true"

  duplicati-web:
    image: lscr.io/linuxserver/duplicati:${DUPLICATI_DOCKER_TAG}
    container_name: duplicati-web
    restart: unless-stopped
    ports:
      - ${DUPLICATI_PORT}:8200
    networks:
      - default
    volumes:
      - ${DUPLICATI_BASE_DIRECTORY}/config:/config
      # - </path/to/backups>:/backups
      - ${DOCKER_BASE_DIRECTORY}:/source
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}

  nextcloud-server:
    image: nextcloud:${NEXTCLOUD_DOCKER_TAG}
    container_name: nextcloud-server
    restart: always
    links:
      - nextcloud-db
      - nextcloud-redis
    ports:
      - ${NEXTCLOUD_PORT}:80
    networks:
      - default
    volumes:
      - ${NEXTCLOUD_BASE_DIRECTORY}/www/html:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME}
      - POSTGRES_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis

  nextcloud-db:
    image: postgres:${NEXTCLOUD_DB_DOCKER_TAG}
    container_name: nextcloud-db
    restart: always
    ports:
      - ${NEXTCLOUD_DB_PORT}:5432
    networks:
      - default
    volumes:
      - ${NEXTCLOUD_DB_BASE_DIRECTORY}/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${NEXTCLOUD_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nextcloud-redis:
    image: redis:${NEXTCLOUD_REDIS_DOCKER_TAG}
    container_name: nextcloud-redis
    restart: always
    ports:
      - ${NEXTCLOUD_REDIS_PORT}:6379
    networks:
      - default
    volumes:
      - ${NEXTCLOUD_REDIS_BASE_DIRECTORY}:/var/lib/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  nextcloud-collabora-web:
    image: collabora/code:${NEXTCLOUD_COLLABORA_DOCKER_TAG}
    container_name: nextcloud-collabora-web
    restart: always
    ports:
      - ${NEXTCLOUD_COLLABORA_PORT}:9980
    networks:
      - default
    environment:
      - domain=collabora.${SERVICE_DOMAIN}
      - username=${NEXTCLOUD_COLLABORA_USERNAME}
      - password=${NEXTCLOUD_COLLABORA_PASSWORD}
      - extra_params=--o:ssl.enable=true

  # plex-server:
  #   image: plexinc/pms-docker:${PLEX_DOCKER_TAG}
  #   container_name: plex-server
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TIMEZONE}
  #     - CLAIM_TOKEN=${PLEX_CLAIM_TOKEN}
  #   volumes:
  #     - ${PLEX_BASE_DIRECTORY}/config:/config
  #     - ${PLEX_BASE_DIRECTORY}/transcode:/transcode
  #     - ${MEDIA_DIRECTORY}:/media

  navidrome-server:
    image: deluan/navidrome:${NAVIDROME_DOCKER_TAG}
    container_name: navidrome-server
    # user: 1000:1000 # should be owner of volumes
    ports:
      - ${NAVIDROME_PORT}:4533
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
    volumes:
      - ${NAVIDROME_BASE_DIRECTORY}/data:/data
      - ${MUSIC_DIRECTORY}:/music:ro

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:${CALIBRE_WEB_DOCKER_TAG}
    container_name: calibre-web
    restart: unless-stopped
    networks:
      - default
    ports:
      - ${CALIBRE_WEB_PORT}:8083
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - ${CALIBRE_WEB_BASE_DIRECTORY}/config:/config
      - ${BOOKS_DIRECTORY}:/books:ro

  gogs-web:
    image: gogs/gogs:${GOGS_DOCKER_TAG}
    container_name: gogs-web
    restart: always
    ports:
      - ${GOGS_PORT}:3000
      - ${GOGS_SSH_PORT}:22
    networks:
      - default
    environment:
      - RUN_CROND=true
    volumes:
      - ${GOGS_BASE_DIRECTORY}/data:/data
    depends_on:
      - gogs-db

  gogs-db:
    image: postgres:${GOGS_DB_DOCKER_TAG}
    container_name: gogs-db
    restart: always
    networks:
      - default
    ports:
      - ${GOGS_DB_PORT}:5432
    environment:
      - POSTGRES_USER=${GOGS_USER}
      - POSTGRES_PASSWORD=${GOGS_DB_PASSWORD}
      - POSTGRES_DB=${GOGS_DB}
    volumes:
      - ${GOGS_DB_BASE_DIRECTORY}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GOGS_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  homer-web:
    image: b4bz/homer:${HOMER_DOCKER_TAG}
    container_name: homer-web
    restart: always
    networks:
      - default
    ports:
      - ${HOMER_WEB_PORT}:8080
    volumes:
      - ${HOMER_WEB_BASE_DIRECTORY}/www/assets:/www/assets
    environment:
      - INIT_ASSETS=0

  audiobookshelf-web:
    image: ghcr.io/advplyr/audiobookshelf:${AUDIOBOOKSHELF_DOCKER_TAG}
    container_name: audiobookshelf-web
    networks:
      - default
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    environment:
      - AUDIOBOOKSHELF_UID=${PUID}
      - AUDIOBOOKSHELF_GID=${PGID}
    volumes:
      - ${AUDIOBOOKS_DIRECTORY}:/audiobooks
      - ${PODCASTS_DIRECTORY}:/podcasts
      - ${AUDIOBOOKSHELF_BASE_DIRECTORY}/config:/config
      - ${AUDIOBOOKSHELF_BASE_DIRECTORY}/metadata:/metadata

  podgrab-web:
    image: akhilrex/podgrab:${PODGRAB_DOCKER_TAG}
    container_name: podgrab-web
    environment:
      - CHECK_FREQUENCY=240
    volumes:
      - ${PODGRAB_BASE_DIRECTORY}/config:/config
      - ${PODCASTS_DIRECTORY}:/assets
    ports:
      - ${PODGRAB_PORT}:8080
    restart: unless-stopped

  drawio-web:
    image: jgraph/drawio:${DRAWIO_DOCKER_TAG}
    container_name: drawio-web
    restart: unless-stopped
    ports:
      - ${DRAWIO_PORT}:8080
      - ${DRAWIO_HTTPS_PORT}:8443
    environment:
      ORGANISATION_UNIT: unit
      ORGANISATION: bewoogie
      CITY: Remote
      STATE: Remote

  bitwarden-server:
    image: vaultwarden/server:${BITWARDEN_DOCKER_TAG}
    container_name: bitwarden-server
    restart: always
    networks:
      - default
    ports:
      - ${BITWARDEN_PORT}:80
      - ${BITWARDEN_HTTPS_PORT}:443
    volumes:
      - ${BITWARDEN_BASE_DIRECTORY}/data:/data/
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "true"

  monitoring-influxdb:
    image: influxdb:${INFLUXDB_DOCKER_TAG}
    container_name: monitoring-influxdb
    restart: always
    ports:
      - ${INFLUXDB_PORT}:8086
    volumes:
      - ${INFLUXDB_BASE_DIRECTORY}/data:/var/lib/influxdb
      - ${INFLUXDB_BASE_DIRECTORY}/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ${INFLUXDB_BASE_DIRECTORY}/init:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}

  monitoring-telegraf:
    image: telegraf:${TELEGRAPF_DOCKER_TAG}
    container_name: monitoring-telegraf
    restart: always
    volumes:
      - ${INFLUXDB_BASE_DIRECTORY}/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  monitoring-grafana:
    image: grafana/grafana-oss:${GRAFANA_DOCKER_TAG}
    container_name: monitoring-grafana
    ports:
      - ${GRAFANA_PORT}:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ${GRAFANA_BASE_DIRECTORY}/var/lib/grafana:/var/lib/grafana

networks:
  default:
    driver: bridge

  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: ovs_eth0
    ipam:
      config:
        - subnet: ${SUBNET_IP_ADDRESS}/22
          gateway: ${GATEWAY_IP_ADDRESS}
          ip_range: ${DNS_IP_ADDRESS}/32
          aux_addresses:
            host: ${HOST_IP_ADDRESS}