version: "2"

services:
  pihole-server:
    image: pihole/pihole:2022.07.1
    container_name: pihole-server
    restart: always
    networks:
      macvlan_network:
        ipv4_address: 192.168.1.200
    cap_add:
      - NET_ADMIN # add if using DHCP in pihole
    volumes:
      - ${PIHOLE_BASE_DIRECTORY}/pihole/:/etc/pihole/
      - ${PIHOLE_BASE_DIRECTORY}/dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 192.168.1.1
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      TZ: ${TIMEZONE}
      ServerIP: 192.168.1.200
      WEBPASSWORD: ${PIHOLE_PASSWORD}

  nginx-server:
    image: jc21/nginx-proxy-manager:2.9.18
    container_name: nginx-proxy
    restart: unless-stopped
    networks:
      macvlan_network:
        ipv4_address: 192.168.1.201
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ${NGNIX_PROXY_MANAGER_BASE_DIRECTORY}/data:/data
      - ${NGNIX_PROXY_MANAGER_BASE_DIRECTORY}/letsencrypt:/etc/letsencrypt
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: "true"

  plex-server:
    image: plexinc/pms-docker:1.28.0.5999-97678ded3
    container_name: plex-server
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - CLAIM_TOKEN=${PLEX_CLAIM_TOKEN}
    volumes:
      - ${PLEX_BASE_DIRECTORY}/config:/config
      - ${PLEX_BASE_DIRECTORY}/transcode:/transcode
      - ${MEDIA_DIRECTORY}:/media

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.19
    container_name: calibre-web
    restart: unless-stopped
    networks:
      - default
    ports:
      - ${CALIBRE_WEB_PORT}:8083
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - ${CALIBRE_WEB_BASE_DIRECTORY}/config:/config
      - ${BOOKS_DIRECTORY}:/books

  gogs-web:
    image: gogs/gogs:0.12
    container_name: gogs-web
    restart: always
    ports:
      - ${GOGS_PORT}:3000
      - ${GOGS_SSH_PORT}:22
    networks:
      - default
    environment:
      - RUN_CROND=true
    volumes:
      - ${GOGS_BASE_DIRECTORY}/data:/data
    depends_on:
      - gogs-db

  gogs-db:
    image: postgres:14
    container_name: gogs-db
    restart: always
    networks:
      - default
    ports:
      - ${GOGS_DB_PORT}:5432
    environment:
      - POSTGRES_USER=${GOGS_USER}
      - POSTGRES_PASSWORD=${GOGS_DB_PASSWORD}
      - POSTGRES_DB=${GOGS_DB}
    volumes:
      - ${GOGS_DB_BASE_DIRECTORY}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GOGS_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  home-assistant-web:
    image: ghcr.io/home-assistant/home-assistant:2022.8.3
    container_name: home-assistant-web
    restart: always
    network_mode: host
    volumes:
      - ${HOME_ASSISTANT_BASE_DIRECTORY}/config:/config
    environment:
      - TZ=${TIMEZONE}

  homer-web:
    image: b4bz/homer:v22.07.2
    container_name: homer-web
    restart: always
    networks:
      - default
    ports:
      - ${HOMER_WEB_PORT}:8080
    volumes:
      - ${HOMER_WEB_BASE_DIRECTORY}/www/assets:/www/assets
    environment:
      - INIT_ASSETS=0

  tailscale-agent:
    image: tailscale/tailscale:v1.29.125
    container_name: tailscale-agent
    hostname: kratos
    privileged: true
    network_mode: host
    volumes:
      - ${TAILSCALE_BASE_DIRECTORY}/var/lib:/var/lib   # State data will be stored in this directory
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    command: tailscaled
    restart: unless-stopped

  audiobookshelf-web:
    image: ghcr.io/advplyr/audiobookshelf:2.1.2
    container_name: audiobookshelf-web
    networks:
      - default
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    environment:
      - AUDIOBOOKSHELF_UID=${PUID}
      - AUDIOBOOKSHELF_GID=${PGID}
    volumes:
      - ${AUDIOBOOKS_DIRECTORY}:/audiobooks
      - ${PODCASTS_DIRECTORY}:/podcasts
      - ${AUDIOBOOKSHELF_BASE_DIRECTORY}/config:/config
      - ${AUDIOBOOKSHELF_BASE_DIRECTORY}/metadata:/metadata

  podgrab-web:
    image: akhilrex/podgrab:1.0.0
    container_name: podgrab-web
    environment:
      - CHECK_FREQUENCY=240
    volumes:
      - ${PODGRAB_BASE_DIRECTORY}/config:/config
      - ${PODCASTS_DIRECTORY}:/assets
    ports:
      - ${PODGRAB_PORT}:8080
    restart: unless-stopped

  node-red:
    image: nodered/node-red:2.2.3-12
    container_name: node-red
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
    ports:
      - ${NODE_RED_PORT}:1880
    networks:
      - default
    volumes:
      - ${NODE_RED_BASE_DIRECTORY}/data:/data

  photoview-server:
    image: viktorstrate/photoview:2
    restart: always
    container_name: photoview-server
    ports:
      - ${PHOTOVIEW_PORT}:80
    depends_on:
      - photoview-db
    volumes:
      - ${PHOTOS_DIRECTORY}:/photos:ro
      - ${PHOTOVIEW_BASE_DIRECTORY}/cache:/app/cache
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=postgres
      - PHOTOVIEW_POSTGRES_URL=postgresql://${PHOTOVIEW_DB_USER}:${PHOTOVIEW_DB_PASSWORD}@photoview-db/${PHOTOVIEW_DB_NAME}
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache

  photoview-db:
    image: postgres:14
    container_name: photoview-db
    restart: always
    networks:
      - default
    ports:
      - ${PHOTOVIEW_DB_PORT}:5432
    environment:
      - POSTGRES_USER=${PHOTOVIEW_DB_USER}
      - POSTGRES_PASSWORD=${PHOTOVIEW_DB_PASSWORD}
      - POSTGRES_DB=${PHOTOVIEW_DB_NAME}
    volumes:
      - ${PHOTOVIEW_DB_BASE_DIRECTORY}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PHOTOVIEW_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  drawio-web:
    image: jgraph/drawio:20.2.3
    container_name: drawio-web
    restart: unless-stopped
    ports:
      - ${DRAWIO_PORT}:8080
      - ${DRAWIO_HTTPS_PORT}:8443
    environment:
      ORGANISATION_UNIT: unit
      ORGANISATION: bewoogie
      CITY: Remote
      STATE: Remote

  bitwarden-server:
    image: vaultwarden/server:1.25.2-alpine
    container_name: bitwarden-server
    restart: always
    networks:
      - default
    ports:
      - ${BITWARDEN_PORT}:80
      - ${BITWARDEN_HTTPS_PORT}:443
    volumes:
      - ${BITWARDEN_BASE_DIRECTORY}/data:/data/
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "true"

  photouploader-server:
    image: filebrowser/filebrowser:s6
    container_name: photouploader-server
    restart: unless-stopped
    networks:
      - default
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${PHOTOS_DIRECTORY}:/photos
      - ${PHOTOUPLOADER_BASE_DIRECTORY}/database/filebrowser.db:/database/filebrowser.db
      - ${PHOTOUPLOADER_BASE_DIRECTORY}/config:/config
    ports:
      - ${PHOTOUPLOADER_PORT}:80

networks:
  default:
    driver: bridge

  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: ovs_eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.200/28
          aux_addresses:
            host: 192.168.1.210