version: "3.3"

services:
  plex-server:
    image: plexinc/pms-docker:1.28.0.5999-97678ded3
    container_name: plex-server
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - CLAIM_TOKEN=${PLEX_CLAIM_TOKEN}
    volumes:
      - ${PLEX_BASE_DIRECTORY}/config:/config
      - ${PLEX_BASE_DIRECTORY}/transcode:/transcode
      - ${MEDIA_DIRECTORY}:/media

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.19
    container_name: calibre-web
    restart: unless-stopped
    networks:
      - default
    ports:
      - ${CALIBRE_WEB_PORT}:8083
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - ${CALIBRE_WEB_BASE_DIRECTORY}/config:/config
      - ${BOOKS_DIRECTORY}:/books

  gogs-web:
    image: gogs/gogs:0.12
    container_name: gogs-web
    restart: always
    ports:
      - ${GOGS_PORT}:3000
      - ${GOGS_SSH_PORT}:22
    networks:
      - default
    environment:
      - RUN_CROND=true
    volumes:
      - ${GOGS_BASE_DIRECTORY}/data:/data
    depends_on:
      - gogs-db

  gogs-db:
    image: postgres:14
    container_name: gogs-db
    restart: always
    networks:
      - default
    ports:
      - ${GOGS_DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${GOGS_USER}
      - POSTGRES_PASSWORD=${GOGS_DATABASE_PASSWORD}
      - POSTGRES_DB=${GOGS_DATABASE}
    volumes:
      - ${GOGS_DATABASE_BASE_DIRECTORY}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GOGS_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  home-assistant-web:
    image: ghcr.io/home-assistant/home-assistant:2022.8.3
    container_name: home-assistant-web
    restart: always
    network_mode: host
    volumes:
      - ${HOME_ASSISTANT_BASE_DIRECTORY}/config:/config
    environment:
      - TZ=${TIMEZONE}

  homer-web:
    image: b4bz/homer:v22.07.2
    container_name: homer-web
    restart: always
    networks:
      - default
    ports:
      - ${HOMER_WEB_PORT}:8080
    volumes:
      - ${HOMER_WEB_BASE_DIRECTORY}/www/assets:/www/assets
    environment:
      - INIT_ASSETS=0

  tailscale-agent:
      image: tailscale/tailscale:v1.29.125
      container_name: tailscale-agent
      hostname: kratos
      privileged: true
      network_mode: host
      volumes:
        - ${TAILSCALE_BASE_DIRECTORY}/var/lib:/var/lib   # State data will be stored in this directory
        - /dev/net/tun:/dev/net/tun
      cap_add:
        - net_admin
        - sys_module
      command: tailscaled
      restart: unless-stopped

  audiobookshelf-web:
    image: ghcr.io/advplyr/audiobookshelf:2.1.2
    container_name: audiobookshelf-web
    networks:
      - default
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    environment:
      - AUDIOBOOKSHELF_UID=${PUID}
      - AUDIOBOOKSHELF_GID=${PGID}
    volumes:
      - ${AUDIOBOOKS_DIRECTORY}:/audiobooks
      - ${PODCASTS_DIRECTORY}:/podcasts
      - ${AUDIOBOOKSHELF_BASE_DIRECTORY}/config:/config
      - ${AUDIOBOOKSHELF_BASE_DIRECTORY}/metadata:/metadata

  podgrab-web:
    image: akhilrex/podgrab:1.0.0
    container_name: podgrab-web
    environment:
      - CHECK_FREQUENCY=240
    volumes:
      - ${PODGRAB_BASE_DIRECTORY}/config:/config
      - ${PODCASTS_DIRECTORY}:/assets
    ports:
      - ${PODGRAB_PORT}:8080
    restart: unless-stopped

  node-red:
    image: nodered/node-red:2.2.3-12
    container_name: node-red
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
    ports:
      - ${NODE_RED_PORT}:1880
    networks:
      - default
    volumes:
      - ${NODE_RED_BASE_DIRECTORY}/data:/data

  photoprism-server:
    image: photoprism/photoprism:220730-bookworm
    container_name: photoprism-server
    working_dir: "/photoprism"
    depends_on:
      - photoprism-db
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - ${PHOTOPRISM_PORT}:2342
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "insecure"
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_SITE_URL: "http://${SERVER_HOST}:${PHOTOPRISM_PORT}/"
      PHOTOPRISM_ORIGINALS_LIMIT: 5000
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"
      PHOTOPRISM_LOG_LEVEL: "info"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_DISABLE_CHOWN: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"
      PHOTOPRISM_DISABLE_FACES: "false"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
      PHOTOPRISM_DISABLE_RAW: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_JPEG_QUALITY: 90
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "photoprism-db:${PHOTOPRISM_DB_PORT}"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "${PHOTOPRISM_DB_USER}"
      PHOTOPRISM_DATABASE_PASSWORD: "${PHOTOPRISM_DB_PASSWORD}"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: "Family photos and other memorable images"
      PHOTOPRISM_SITE_AUTHOR: "Bewoogie Family"
      PHOTOPRISM_UID: ${PUID}
      PHOTOPRISM_GID: ${PGID}
    volumes:
      - ${PHOTOS_DIRECTORY}/Emily Baron:/photoprism/originals/emilybaron
      - ${PHOTOS_DIRECTORY}/TJ Maynes:/photoprism/originals/tjmaynes
      - ${PHOTOPRISM_BASE_DIRECTORY}/storage:/photoprism/storage

  photoprism-db:
    image: mariadb:10.8
    container_name: photoprism-db
    restart: unless-stopped
    ports:
      - ${PHOTOPRISM_DB_PORT}:3306
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - ${PHOTOPRISM_DB_BASE_DIRECTORY}:/var/lib/mysql
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "${PHOTOPRISM_DB_USER}"
      MARIADB_PASSWORD: "${PHOTOPRISM_DB_PASSWORD}"
      MARIADB_ROOT_PASSWORD: "${PHOTOPRISM_DB_ROOT_PASSWORD}"

  drawio-web:
    image: jgraph/drawio:20.2.3
    container_name: drawio-web
    restart: unless-stopped
    ports:
      - ${DRAWIO_PORT}:8080
      - ${DRAWIO_HTTPS_PORT}:8443
    environment:
      PUBLIC_DNS: ${SERVER_HOST}
      ORGANISATION_UNIT: unit
      ORGANISATION: bewoogie
      CITY: Remote
      STATE: Remote
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://${SERVER_HOST}:${DRAWIO_PORT} || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s

  bitwarden-server:
    image: vaultwarden/server:1.25.2-alpine
    container_name: bitwarden-server
    restart: always
    ports:
      - ${BITWARDEN_PORT}:80
      - ${BITWARDEN_HTTPS_PORT}:443
    volumes:
      - ${BITWARDEN_BASE_DIRECTORY}/data:/data/
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "true"

networks:
  default:
    driver: bridge
